version: 2.1
orbs: 
  windows: circleci/windows@4.1.1
jobs:
  build:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            choco install qt-sdk-windows-x64-mingw_sjlj
            choco install sqlite
            choco install opencv
            choco install -y visualstudio2019testagent --package-parameters "--includeRecommended --includeOptional"
workflows:
  version: 2
  build-and-test:
    jobs:
      - build