version: 2.1
orbs: 
  windows: circleci/windows@4.1.1
jobs:
  build:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            choco install qt-sdk-windows-x64-mingw_sjlj
            #choco install sqlite
            #choco install opencv
            choco install visualstudio2022buildtools
      - run:            
         command: | 
          $(echo hello | Out-Host; $?) -and $(echo world | Out-Host; $?)
          mkdir build-win
          cd build-win
         shell: powershell.exe vcvarsall.bat x86_amd64
workflows:
  version: 2
  build-and-test:
    jobs:
      - build