version: 2.1
orbs: 
  windows: circleci/windows@4.1.1
jobs:
  build-for-windows:
    executor:
      name: win/default # executor type
    steps:
      - checkout
      - run:
          name: "building windows version"
          command: | 
            mkdir build
            cd build
            cmake.. 
            make filegrunt
workflows:
  build_and_test:
    jobs:
      - build-for-windows  
