version: 2.1
orbs: 
  windows: circleci/windows@4.1.1
jobs:
  build:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            #choco install visualstudio2019buildtools
            #choco install vcbuildtools
            #choco install sqlite --version 3.38.2 -y
            #choco install opencv --version 4.5.5 -y
            #choco install qt5-default --version 5.15.2.20211228 -y
      - run:            
         command: | 
          #$(echo cl | Out-Host; $?)
          #mkdir build-win
          #cd build-win
          dir
          cd "c:\%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Community\Common7\Tools\"
          #"%ProgramFiles(x86)%\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat" cl
         #shell: powershell.exe cl
workflows:
  version: 2
  build-and-test:
    jobs:
      - build