name: filegrunt
version: "0.0.0-dev"
summary: Image File Comparison Utility
description: |
  Utility to identify duplicate files/images and allow the user to move the duplicates to a location for archival or deletion.
confinement: devmode
icon: images/icon.png
base: core18
grade: devel
type: app

parts:
  filegrunt:
    plugin: autotools
    source-type: tar
    source: https://github.com/filegrunt/filegrunt.git
    build-packages:
      - build-essential
      - g++
      - libsqlite3-dev
      - cmake
      - git
      - qtbase5-dev
      - qttools5-dev
      - qttools5-dev-tools
    stage-packages:
      - libsdl-sound1.2


apps:
  filegrunt:
    command: filegrunt
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
      "DISABLE_WAYLAND": "1"
