name: filegrunt
version: "0.0.0"
base: core20
compression: lzo
summary: Image File Comparison Utility
description: |
  Utility to identify duplicate files/images and allow the user to move the duplicates to a location for archival or deletion.
confinement: strict
grade: devel
icon: images/icon.png
type: app

architectures:
  - build-on: amd64
    run-on: amd64

apps:
  filegrunt:
    command: usr/local/bin/filegrunt
    command-chain:
      - bin/desktop-launch
      - usr/local/bin/filegrunt
    desktop: usr/local/share/applications/filegrunt.desktop
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
      XLOCALEDIR: '$SNAP/usr/share/X11/locale'
      LOCPATH: '$SNAP/usr/lib/locale'
      GTK_PATH: $SNAP/lib/gtk-2.0
      GTK_DATA_PREFIX: $SNAP
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
      XDG_CONFIG_HOME: '$HOME/.config'
      XKB_CONFIG_ROOT: '$SNAP/usr/share/X11/xkb'
      XDG_CONFIG_DIRS: '$SNAP/etc/xdg:$XDG_CONFIG_DIRS'
      XDG_DATA_HOME: '$SNAP/usr/share'
      QT_QPA_PLATFORMTHEME: qt5ct
    plugs:
      - desktop
      - desktop-legacy
      - opengl
      - gsettings
      - home
      - unity7
      - wayland
      - x11
      - removable-media

build-packages:
  - build-essential
  - g++
  - libsqlite3-dev
  - cmake
  - git
  - qtbase5-dev
  - qttools5-dev
  - qttools5-dev-tools
  - libopencv-dev
  - libatlas-base-dev

parts:
  filegrunt:
    plugin: cmake
    source: .
  desktop-qt5:
    build-packages:
      - qtbase5-dev
      - dpkg-dev
      - libgtk-3-dev
      - libopencv-dev
    make-parameters:
      - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
      - libc6
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - ibus-gtk3
      - libibus-1.0-5
      - libgtk2.0-0
      - qt5-image-formats-plugins
      - libopencv-core4.2
      - libopencv-highgui4.2
      - libopencv-imgcodecs4.2
      - libopencv-imgproc4.2
    organize:
      usr/lib/*-linux-gnu/blas/*: usr/lib/
      usr/lib/*-linux-gnu/lapack/*: usr/lib/
      usr/lib/*-linux-gnu/gio/*: usr/lib/