name: filegrunt
version: "0.0"
summary: Image File Comparison Utility
description: |
  Utility to identify duplicate files/images and allow the user to move the duplicates to a location for archival or deletion.
###confinement: devmode
confinement: strict
icon: images/icon.png
base: core20
compression: lzo
grade: devel
type: app

architectures:
  - build-on: amd64
  ###- build-on: arm64
  ###- build-on: armhf
  ###- build-on: ppc64el

apps:
  filegrunt:
    #####command: /usr/local/bin/filegrunt
    command: /usr/local/bin/filegrunt
    environment:
      DISABLE_WAYLAND: "1"
    plugs:
      - desktop
      - gsettings
      - home
      - wayland
      - x11
      - removable-media

build-packages:
  - build-essential
  - g++
  - libsqlite3-dev
  - cmake
  - git
  - qtbase5-dev
  - qttools5-dev
  - qttools5-dev-tools
  - libopencv-dev

parts:
  filegrunt:
    plugin: nil
    source-type: git
    source: https://github.com/filegrunt/filegrunt.git
    stage-packages:
      - libgl1
      - libglu1-mesa
      - libglx0
