name: filegrunt
version: "0.0.0-dev"
summary: Image File Comparison Utility
description: |
  Utility to identify duplicate files/images and allow the user to move the duplicates to a location for archival or deletion.
confinement: devmode
icon: images/icon.png
base: core18
grade: devel
type: app

parts:
  filegrunt:
    plugin: nil
    source: https://github.com/filegrunt/filegrunt.git
    build-packages:
      - build-essential
      - g++
      - libsqlite3-dev
      - cmake
      - git
      - qtbase5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - libqt5scintilla2-dev
      - libopencv-dev
    stage-packages:
      - libgl1
      - libglu1-mesa
      - libglx0

apps:
  filegrunt:
    command: /mnt/ntfs1/Development/CLionProjects/filegrunt/cmake-build-debug/filegrunt
    environment:
      "DISABLE_WAYLAND": "1"
